######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 26 15:44:31 2013
######################################################################

QT       += core

QT       -= gui

QT       += network

TARGET = networking
CONFIG   += console
CONFIG   -= app_bundle

TEMPLATE = app


SOURCES += main.cpp \
    ../COMP3004/server.cpp

HEADERS += \
    ../COMP3004/server.h
